# Generated by Django 4.2.4 on 2023-08-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
